### ISSUE TITLE
Safari 9

### ISSUE THREAD

**Issue by iamjonbradley** [rndme/download#10]
This does not seem to work on safari 9+

http://pagedemos.com/sxks39b72aqb/1 
http://pagedemos.com/sxks39b72aqb/2

generate nothing 

http://pagedemos.com/sxks39b72aqb/3

Failed to load resource: Frame load interrupted

**Comment by rndme** [comment]
grrrr. the new IE, i swear... looking into it, thanks for the heads-up.

**Comment by dangnelson** [comment]
+1

**Comment by dannewoo** [comment]
++1

**Comment by rndme** [comment]
try the output version, safari is not a fan of iframes : 

http://pagedemos.com/sxks39b72aqb/output/

**Comment by rosivanov** [comment]
Still doesn't work with safari (

**Comment by talltorp** [comment]
I am having trouble with getting the output version to work as well.

When I visit the link you posted, I get this message

![image](https://cloud.githubusercontent.com/assets/1172400/14812654/5c36d0ec-0b9e-11e6-9b92-f007e0079817.png)

When I click the OK button, Safari gives me this error

![image](https://cloud.githubusercontent.com/assets/1172400/14812699/8e857f4e-0b9e-11e6-88fb-b15e91fc57a7.png)

I am using Safari 9.1 on Mac.
Please let me know if you need any help in finding the error.

**Comment by rndme** [comment]
that should have been fixed by https://github.com/rndme/download/commit/cfbfddb6307e971296d019b2dc2a39cf888d1caa , but the demos were using a stale copy of the script.

Some of the demo's also won't work in safari because pagedemos (and everyone else like fiddle) uses iframes, which safari doesn't like. I've updated the demo's script copy, and i'll see about replacing the "hosting" with something more compatible.

Thanks for the heads up!
