### ISSUE TITLE
URL characters replaced by Dashes

### ISSUE THREAD

**Issue by X-Raym** [rndme/download#14]
Hi,
When using download.js, some characters became dashes.
http:// became http--- for exemple.

tested [codepen with debug mod](http://s.codepen.io/X-Raym/debug/KdjrrX).

Thanks for your support !

**Comment by rndme** [comment]
the 2nd argument takes a file name, not a url. Different OSes restrict different chars in filenames, but no OS will allow `/`or `:`. Since this is out of download.js's control (it's the OS stripping chars, not JS), i'm closing this issue. if you want to use the filename from the demo's link variable as a filename, in the download() call, replace `link` with `link.split('/').pop()` to grap just the last segment. thanks for using the script and taking the time to report your problem, even if i can't fix this one...

**Comment by X-Raym** [comment]
Thanks for the infos !
Maybe I missed something then, how coulf I link to an absolute download URL ? I need the full path, only the file name is not enough.
Thanks for the infos !

**Comment by rndme** [comment]
you can't specify a local download path, that must be set by the browser, with suggestions from the OS. the only way to save a file is to use the download mechanisms provided, which allows just a custom file name, not a folder. otherwise, malicious hackers could force a download into eg. c:\windows\system32\ or whatever, and that would be bad.

**Comment by X-Raym** [comment]
Ok,
But my question was not 'where to save the file on my computer', it was 'how I define the source URL of the file'.
Download-js is able to download files from a URL and http request, right ?
Thanks again for your support !

**Comment by rndme** [comment]
Ahh, i understand now... There is no support for feeding it a url. i've gotten a couple comments asking about that, but i don't have any code ready for that. there are some examples of how to accomplish that task, ex: the last post on https://github.com/rndme/download/issues/4, but nothing built-in, yet. binary files like audio are particularly troublesome in that they can't be readily downloaded with jQuery, only vanilla. i will re-open this issue and keep it around as a reminder until i can add the direct url download capability people have been asking for. thanks for keeping up and your intrest in the library. Hopefully, you can adopt an example to work for you until we can get built-in url download support.

**Comment by rndme** [comment]
ok, since 4.1, you can download files from a url with a single argument. `download( strURL);`... note that downloadable files  need to reside on the same server as your html page, or the served files must have CORS headers added (somewhat rare). At any rate, this is as good as we can do with the security restrictions in-place by all major browsers. if you need to over-ride the mime type or file name, you can modify the short workaround routine for ajax i linked to.

**Comment by X-Raym** [comment]
Thanks for all the infos !
It leads me to a solution involving htaccess:
https://perishablepress.com/stupid-htaccess-tricks/#usa4
Cheers ! :)

**Comment by X-Raym** [comment]
EDIT: no in fact your method is far better in my case. Thanks :)
