### ISSUE TITLE
Need to add option to specify download location

### ISSUE THREAD

**Issue by sambsa** [rndme/download#19]
How can I specify path? For example if I want to download to my Desktop in my local computer?

**Comment by rndme** [comment]
From download.js, you cannot adjust the path: it's entirely determined by the browser and OS. Some browsers allow you always save a certain type of file (instead of asking to save/open), and most browsers allow you set a custom location for _all_ downloads, but i don't know of any that let you save certain files certain place. Sorry, but there's nothing i or any other code can do about that since the browser call the shots for us.
