### ISSUE TITLE
Great library thanks!

### ISSUE THREAD

**Issue by yegodz** [rndme/download#2]
Safari still refuses to download... tries to open up the file in a new tab or window. Any way to workaround this? I need to be able to save a client side code generated file in blob or objectURL format to a user's downloads folder.

**Comment by rndme** [comment]
i hear you, i'm mad at safari for being weird. it has slowly been getting better, it used to not support any of the technologies needed to pull this off well. it has been several months since i last played around with it, maybe the latest will finally let allow first-class downloads. i'll check into it and let you know what i figure out sometime this week when i get my mac back. thanks for the feedback.
