### ISSUE TITLE
docx, ods

### ISSUE THREAD

**Issue by deatk** [rndme/download#20]
Hi,
in my app i was using just this piece of js:

`var link = document.createElement("a");
                link.download = dataItem.Filename;
                link.href = data;
                link.click();`

where data is the data uri with mime type etc...
this is working perfectly on chrome, but not in ie
so i used your library, and it's perfect for ie
the only issue is that is not working with documents like docx, ods...

**Comment by rndme** [comment]
there have been other reports of office problems too, and i'm look into it. Thanks for the heads-up, and i'll let you know what we find.

**Comment by deatk** [comment]
i have already foud a solution.

for ie browser i download a blob from the encoded string
and it works for any kind of files.

`
function b64toBlob(b64Data, contentType, sliceSize) {
  contentType = contentType || '';
  sliceSize = sliceSize || 512;

  var byteCharacters = atob(b64Data);
  var byteArrays = [];

  for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    var slice = byteCharacters.slice(offset, offset + sliceSize);

    var byteNumbers = new Array(slice.length);
    for (var i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }

    var byteArray = new Uint8Array(byteNumbers);

    byteArrays.push(byteArray);
  }

  var blob = new Blob(byteArrays, {type: contentType});
  return blob;
}

var blob = b64toBlob(b64Data, contentType);
var blobUrl = URL.createObjectURL(blob);

window.location = blobUrl;
`

for chrome or other browsers it's really really easyer, just 4 lines of code for all kind of files:

`
function downloadURI(uri, name) {
  var link = document.createElement("a");
  link.download = name;
  link.href = uri;
  link.click();
}
`

**Comment by rndme** [comment]
I'm glad to see you got something working and thanks for the feedback.  As an avid JS golfer, i certainly appreicieate the simplitiy of single-input single-browser solutions. Download needs to support other browsers (ie, safari, android, etc) and different forms of input (str, blob, dataURL, binary arrays, etc), which adds A LOT of complexity. I might cut a "legacy-free" version with a much smaller codebase at some point when IE can be declared legally dead...

That b64toBlob() function basically re-creates the [dataURLtoBlob routine](https://github.com/rndme/download/blob/master/download.js#L79) used in download(), which makes me curious about why it didn't work for your dataURLs.

Even though you figured something out, would you might posting a copy of a dataURL that download() didn't like, so that i can see about fixing it for the guy? they might not be so clever about figuring it out themselves, so if we could help them out, it would be a win.

Thanks again for your interest in the project and taking time to share your thoughts and ideas.

**Comment by deatk** [comment]
and my problem is that i cannot read your code, so i was not able to combine my changes inside your function.

i was using your code only for the ie version, because on the chrome it was not working in my solution, i could see only a message "downloading" appearing on the screen, but nohing was happening.

**Comment by rndme** [comment]
thanks for dropping me a line, and I'm glad you got something working for you.
