### ISSUE TITLE
Expose the limitations programatically

### ISSUE THREAD

**Issue by pavankumarkatakam** [rndme/download#28]
This is a great lib for downloading, event though it is supported in modern browsers some people are in older browser for them i want to show which file is download or not download, to do so expose the limitations via isChromeSupoort,isIESupport like that variables.

**Comment by pavankumarkatakam** [comment]
is there anybody?

**Comment by rndme** [comment]
the problem is that it's not one browser or the other that work, and even on browsers that work, older versions have some limits, like Blob URLs in FireFox 3.5 for example. As a result, i'm not sure how we can easily implement such functionality, But, since non-IE usually self-updates, we can assume that anything after IE10 (minus safari) will work as expected. If you have a great way to add this on without much complication, please re-open or submit a PR.
