### ISSUE TITLE
Error downloading PDF from IE: InvalidCharacterError

### ISSUE THREAD

**Issue by yamizukin** [rndme/download#29]
Using base64 encoded content, I can download text and images. I can also download PDFs in chrome.

However, I'm getting an error when downloading the same PDF in Internet Explorer 11.

[index.txt](https://github.com/rndme/download/files/350717/index.txt)

How can I fix this?

**Comment by rndme** [comment]
I can't reproduce this, but i don't have your file either...

Can you please post a link to a pdf file that doesn't work in IE11?

**Comment by maillig** [comment]
@yamizukin 

I think i have found the problem:

1. download.js uses the atob() method to decode the base64. 
2. It breaks in Internet Explorer 11 if the base64 string contains newlines. 

[Stackoverflow with simular issue](https://stackoverflow.com/questions/9786508/javascript-atob-returning-string-contains-an-invalid-character)

The fix is simple, just remove the line breaks:

var base64String = "DYWxpYnJpL0Vu Y29kaW5nL1dpbkFuc2lFbmNvZGluZy9Gb250RGVz....."

if (window.navigator && window.navigator.msSaveOrOpenBlob) { 
  // IE specific code
   base64String= base64String.replace(/\s/g, '');
}
And to download:

download("data:application/pdf;base64," + base64String, "fileName", "application/pdf");

**Comment by rndme** [comment]
base64 should not contain newlines anyway.
