### ISSUE TITLE
Simple rename doesn't work. Eg.: download('http://i.imgur.com/7fypLpI.jpg', 'new.jpg');

### ISSUE THREAD

**Issue by EphramDoyle** [rndme/download#43]
Hi!
This script is very useful. Thanks for sharing.

I've tried with:
download('http://i.imgur.com/7fypLpI.jpg', 'new.jpg');
download('http://i.imgur.com/7fypLpI.jpg', 'new.jpg', 'image/jpg');
download('http://i.imgur.com/7fypLpI.jpg', 'new.jpg', 'image/jpeg');

And I can not open the image because it contains errors in the header.

How to solve it?

**Comment by ArunaBalavijay** [comment]
As mentioned in the below stack overflow thread , you can achieve the same as below.

[http://stackoverflow.com/questions/40923414/best-method-to-download-a-file-from-a-button-compatible-with-chrome-and-ie/40923811](url)

`function downloadImage(event, url, fileName) {
  event.preventDefault();

  if(window.download && url) {   
     fileName = fileName || url.split('/').pop().split('?')[0];
     var ajax = new XMLHttpRequest();
        		ajax.open( 'GET', url, true);
        		ajax.responseType = 'blob';
        		ajax.onload= function(e){ 
				  download(e.target.response, fileName, 'application/octet-stream');
				};
        		setTimeout(function(){ ajax.send();}, 0); // allows setting custom ajax headers using the return:
			    return ajax;
  }
}`

**Comment by rndme** [comment]
to keep the common usage simple, URLs need to be spec'd as one argument, which means there's no room to pass a custom file name. you could wrap the download() function to a downloadFile() function that does something like the code ArunaBalavijay shows, but i can't support custom auto-url downloading without breaking something else. I won't ever break existing functionality by a new update because a lot of folks use this lib unmanaged. That said, it's a common request and maybe i can do something about it; i'll think about it... Thanks for taking the time to improve this project!
